<<<<<<< HEAD
# version: "3.9"

# services:

#   db:
#     image: postgres:15
#     container_name: postgres_db
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     env_file:
#       - .env

#   web:
#     build:
#       context: .
#       dockerfile: docker/django/Dockerfile
#     container_name: django_app
#     volumes:
#       - .:/app
#     env_file:
#       - .env
#     depends_on:
#       - db

#   nginx:
#     build:
#       context: .
#       dockerfile: docker/nginx/Dockerfile
#     container_name: nginx_server
#     ports:
#       - "80:80"
#     depends_on:
#       - web

# volumes:
#   postgres_data:
=======
#version: "3.9"

>>>>>>> 8356694 (Setup Dockerized Django project and fixed template errors)
services:
  web:
    build:
      context: .
<<<<<<< HEAD
      dockerfile: docker/django/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000 --settings=config.settings.dev
=======
      dockerfile: docker/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Reference
    #ports:
     # - "8000:8000"
    env_file:
      - env/.env.dev
    depends_on:
      - db

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: epbr_db
      POSTGRES_USER: epbr_user
      POSTGRES_PASSWORD: epbr123
    volumes:
      - postgres_data:/var/lib/postgresql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles  # Reference
    depends_on:
      - web
    

volumes:
  static_volume:
  postgres_data:
>>>>>>> 8356694 (Setup Dockerized Django project and fixed template errors)
