services:
  db:
    image: postgres:15
    container_name: pbr_postgres_pro
    environment:
      - POSTGRES_DB=pbr_pro_db
      - POSTGRES_USER=pbr_admin
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_pro_data:/var/lib/postgresql/data

  web:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    container_name: pbr_web_pro
    ports:
      - "80:8000"
    env_file:
      - ../../.env.prod
    environment:
    DJANGO_SETTINGS_MODULE: config.settings.prod
    depends_on:
      - db

volumes:
  postgres_pro_data: